name: ChewCrew
author: Wafflehaus

dependencies:
  polymer: ">=0.15.0 <0.16.0"
  core_elements: ">=0.4.0+2 <0.5.0"
  paper_elements: ">=0.5.0 <0.6.0"
  browser: "any"

transformers:
- polymer:
    entry_points: web/index.html

dev_dependencies:
  unittest: "any"

environment:
  sdk: "any"